# Generated by Django 4.1.1 on 2022-11-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_account', '0004_cart_razor_pay_order_id_cart_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_img',
        ),
    ]
