# Generated by Django 4.1.2 on 2022-10-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant_products_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='products_category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='products_name',
            new_name='product_name',
        ),
    ]
