# Generated by Django 4.1.2 on 2022-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_color_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='color_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size_price',
            field=models.IntegerField(default=0),
        ),
    ]
