# Generated by Django 4.1.2 on 2022-10-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
