# Generated by Django 4.1.2 on 2022-10-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_quantity',
        ),
    ]
